name: Build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-10.15]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile
